name: Auto Export

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:  
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        cache: false

    - name: Install Packwiz
      run: make update-packwiz

    - name: Create short commit SHA
      id: vars
      run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$shortSha" >> $GITHUB_ENV

    - name: Export
      run: |
        make refresh
        make export

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Adrenaline-dev-${{ env.COMMIT_SHORT_SHA }}"
        path: build/fabric